### ISSUE TITLE
IntegerDivisionByZeroException

### ISSUE THREAD

**Issue by LukasKarer** [edasandesu/flutter_image_slideshow#15]
Doesn't matter what I do, if height and width are set or not, I get a IntegerDivisionByZeroException.

`The following IntegerDivisionByZeroException was thrown building:
IntegerDivisionByZeroException

When the exception was thrown, this was the stack: 
#0      int.% (dart:core-patch/integers.dart:45:7)
#1      ImageSlideshowState.build.<anonymous closure> (package:flutter_image_slideshow/src/image_slideshow.dart:148:42)
#2      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:485:22)
#3      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1376:28)
#4      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1306:67)
#5      Iterable.forEach (dart:core/iterable.dart:325:35)
#6      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1353:24)
#7      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1282:7)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#17     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:237:11)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#30     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#36     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#42     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#46     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#52     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#66     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#69     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#71     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#73     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#74     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#83     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#84     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#93     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#97     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#99     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#102    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#103    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#107    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#111    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#112    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#116    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#118    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1405:37)
#119    SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1306:35)
#120    Iterable.forEach (dart:core/iterable.dart:325:35)
#121    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1353:24)
#122    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1282:7)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#126    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#130    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#131    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#132    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:237:11)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#134    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#135    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#136    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#138    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#140    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#143    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#144    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#145    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#146    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#147    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#151    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#153    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#154    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#156    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#157    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#159    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#164    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#165    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#166    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#167    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#170    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#173    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#175    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#178    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#179    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#180    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#181    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#182    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#184    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#187    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#188    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#189    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#191    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#192    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#193    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#194    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#195    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#196    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#197    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#201    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#202    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#203    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#204    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#205    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#208    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#209    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#213    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#217    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#219    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
#220    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#221    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#222    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#223    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#224    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#227    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#228    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#229    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#230    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#231    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#232    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#233    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#234    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#235    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#236    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#237    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#238    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#241    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#243    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#245    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#249    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#251    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#252    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#253    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#254    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#255    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#256    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#257    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#258    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#259    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#260    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#261    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#262    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#263    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#264    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#265    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#266    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#268    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#269    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#270    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#271    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#272    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#273    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#274    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#275    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#276    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#277    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#278    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#279    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#281    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#282    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#283    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#284    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#285    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#286    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#287    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#288    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#289    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#290    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#291    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#292    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#293    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#294    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#295    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#296    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#297    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#298    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#299    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#300    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#301    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#302    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#303    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#304    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#305    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#306    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#307    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#308    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#309    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#310    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#312    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#313    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#314    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#315    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#316    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#318    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#319    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#320    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#321    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#322    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#323    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#324    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#325    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#326    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#327    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#328    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#329    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#330    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#333    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#334    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#335    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#336    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#337    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#338    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#339    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#340    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#341    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#342    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#343    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#344    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#345    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#346    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#347    StatelessElement.update (package:flutter/src/widgets/framework.dart:4956:5)
#348    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#349    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#350    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#351    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#352    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#353    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#354    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#355    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#356    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#357    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#358    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#359    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#360    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#361    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#362    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#363    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#364    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#365    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#366    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#367    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#368    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#369    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#370    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#371    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#372    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#373    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#374    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#375    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#376    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#377    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)`

**Comment by edasandesu** [comment]
@LukasKarer 
This exception occurs when the length of items is zero.
To avoid this exception, please make sure  to add at least one widget to the children.

**Comment by alodevloper** [comment]
@edasandesu 
how to use for loop in children ?
